# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8536ba6662ab4f879ac5ee53e0686c34dc1e581a663336984227774f2364d2c6b560de9a0fc0d45e2703669c611be1b4799e1bdd45e121752595c82f725d25cb

test:
  secret_key_base: 36eb69c478b74641252a3b7e31f127478b0e9ee2d5f58b0f609226bba0f8961bc58f0f36202f3ff4bed10fe342d47c1ac55034af9d502bcbc75c529683c986ca

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
